name: "Request Help"
description: Stuck? Ask for help!
title: "help request: "
body:
  - type: markdown
    attributes:
      value: |
        _The more information you share, the faster we can help you._

        Prior to opening the issue, please make sure that you:

        - Use English to communicate.
        - Search the [open issues](https://github.com/deamogo/uipaas-home/issues) and [discussion forum](https://github.com/deamogo/uipaas-home/discussions) to avoid duplicating the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue you are facing and what you need help with.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Share your environment details. Reports without proper environment details will likely be closed.
      value: |
        - OS: macos
        - go sdk version: 1.21.4
        - ...
    validations:
      required: true
