version: "3.3"
services:

  mysql:
    image: mysql:8.0.29
    container_name: ${DOCKER_PREFIX}-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: uipaas-home
    # ports:
    #   - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql/init.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./mysql/log:/var/log/mysql
      # - ./mysql/data:/var/lib/mysql
      # - ./mysql/conf:/etc/mysql/conf.d
    # command: 
    #   [--character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      # start_period: 30s
    networks:
      - uipaashome
  
  home:
    image: uihome
    env_file: 
      - .env
    build:
      dockerfile: ${BACKEND_HOME}/Dockerfile
      context: .
      args:
        - APP_HOME=${APP_HOME}
    container_name: ${DOCKER_PREFIX}-uipaas
    restart: always
    volumes:     
      - ${BACKEND_HOME}:${APP_HOME}
      - ${BACKEND_HOME}/config.yaml:${APP_HOME}/config.yaml
      - /etc/localtime:/etc/localtime
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
    ports:
      - 9000:9000
      # - "443:443"
      - 5000:5000
      # - ${BACKEND_PORT}:8080
    command: [ "/home/uipaashome/backend/banlaunch.sh" ]
    extra_hosts:
      - host.docker.internal:host-gateway
    links:
      - mysql
    networks:
      - uipaashome
    depends_on:
      # - mysql
      mysql:
        condition: service_healthy

networks:
  uipaashome:
    # external: true
