name: ci

on:
  push:
    branches:
      - 1127/feat-frontnd
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: check version ,test
    #运行环境,最新的乌班图系统
    runs-on: ubuntu-latest
    steps:
      #检出代码
      - name: checkout
        uses: actions/checkout@master
      #检查版本
      - name: yarn version
        run: yarn -v

      - name: node version
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: node -v
      - name: install dependencies & test
        working-directory: ./front
        run: |
          yarn
          yarn test