# https://github.com/golangci/golangci-lint
name: Continuous Integration
on:
  push:
    # prevent duplication of tests with
    # `pull_request` event
    branches:
      - main
  pull_request:

jobs:
  run-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go Environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.21.4'
      - name: Run Unit Test Suites
        working-directory: ./backend
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.48.2
          make test
